---
- name: APT UPDATE ON 192.168.88.248 SERVER
  hosts: 192.168.88.248
  gather_facts: no

  tasks:
   - name: Update APT REPO
     become: yes
     apt:
      update_cache: yes
   - name: Run apt update and save output to location
     become: yes
     shell: apt update > /tmp/apt_update_output.txt

   - name: Fetch apt update output to local machine
     become: yes
     fetch:
      src: /tmp/apt_update_output.txt
      dest: /tmp/apt_update_output.txt
      conn_host: 192.168.88.244
      flat: yes
    delegate_to: localhost
