---
- name: APT UPDATE ON 192.168.88.248 SERVER
  host: 192.168.88.248
  ansible.builtin.apt:
    name: "*"
    state: latest
  
  tasks:
    - name: Echo Hello World
      command: echo "Hello, World!"
