---
- hosts: 192.168.88.22
  tasks:
    - name: Installing mysql
      apt: name=mysql state=latest
    - name: Starting mysql Service
      service:
        name: mysql
        state: started
  tasks:
    - name: Uninstalling Nano
      apt: name=nano state=absent
