- hosts: 192.168.88.22
  tasks:
    - name: STOP nginx
      service:
          name: nginx
          state: stopped
    - name: Uninstalling nginx
      apt: name=nginx state=absent
  tasks:
     - name: Installing Nano
       apt: name=nano state=present
